import type { ToolEngine } from '../core/engines/types';
import { generateFromTemplates } from '../core/engines/helpers';
import { registerEngine } from '../core/engines/registry';

const templates = [
  'Global {industry} market: {tam}, growing {growth} annually. Key segment: {segment}.',
  '{industry} TAM estimate: {tam} in {year}. Growth driver: {driver}.',
  'Market snapshot — {industry}: {tam} total, {segment} sub-segment expanding at {growth}.',
  'The {industry} industry is worth {tam}, with {segment} as the fastest-growing slice ({growth}).',
  'Size check for {industry}: {tam} TAM, {segment} SAM, driven by {driver}.',
  '{industry} market research: {tam} globally. {segment} alone accounts for 30-40%. Growth: {growth}.',
  'If you target the {segment} corner of {industry}: {tam} addressable market, {growth} CAGR.',
  '{industry} breakdown — Total: {tam}. Fastest segment: {segment} at {growth}. Catalyst: {driver}.',
  'Solopreneur opportunity in {industry}: {segment} sub-market worth {tam}, growing {growth} YoY.',
  'Market sizing for {industry}: {tam} TAM, {segment} SOM, powered by {driver}. {growth} growth.',
  'The "{industry}" space: {tam} today, projected to hit {projected} by {year} driven by {driver}.',
  'Top-down estimate for {industry}: {tam} worldwide. Bottom-up: {segment} at {growth} CAGR.',
  'Competitive landscape in {industry}: {tam} market, {segment} niche growing {growth}. Entry via {driver}.',
  '{industry} is a {tam} industry. The {segment} segment is the one to watch — {growth} growth rate.',
  'For a solopreneur entering {industry}: aim for {segment} ({tam}), {growth} annual growth, fueled by {driver}.',
];

const wordPools: Record<string, string[]> = {
  industry: [
    'SaaS & cloud software',
    'creator economy',
    'e-learning & online education',
    'health & wellness tech',
    'fintech & personal finance',
    'DTC e-commerce',
    'remote work tools',
    'AI productivity software',
    'podcasting & audio',
    'subscription box market',
    'digital marketing tools',
    'home fitness equipment',
    'pet care & services',
    'plant-based food',
    'mental health apps',
    'cybersecurity for SMBs',
    'sustainable fashion',
    'gig economy platforms',
    'senior care technology',
    'smart home devices',
  ],
  tam: [
    '$2B-$5B',
    '$5B-$15B',
    '$15B-$50B',
    '$50B-$150B',
    '$150B-$300B',
    '$300B+',
    '$500M-$2B',
    '$10B-$30B',
    '$30B-$80B',
    '$100B-$250B',
    '$1B-$3B',
    '$8B-$25B',
    '$200B+',
    '$40B-$100B',
    '$3B-$8B',
  ],
  growth: [
    '8-12%',
    '14-18%',
    '18-25%',
    '25-35%',
    '35%+',
    '10-15%',
    '5-8% (mature)',
    '20-30%',
    '12-16%',
    '30-40%+',
    '15-22%',
    '40%+ hypergrowth',
    '7-10%',
    '22-28%',
    '11-14%',
  ],
  segment: [
    'SMB-focused tools',
    'enterprise upmarket',
    'mobile-first experiences',
    'AI/ML-powered features',
    'marketplace & platform plays',
    'subscription & membership',
    'API & developer tools',
    'consumer mobile apps',
    'B2B workflow automation',
    'content & media',
    'analytics & insights',
    'community-driven products',
    'no-code/low-code tools',
    'micro-SaaS for verticals',
    'personalization & recommendations',
  ],
  driver: [
    'AI adoption across mid-market companies',
    'shift to remote and async work',
    'rising freelance and solopreneur population',
    'smartphone penetration in emerging markets',
    'aging population and senior care needs',
    'climate-conscious consumer spending',
    'regulatory changes forcing compliance upgrades',
    'growing creator and influencer economy',
    'post-pandemic digital transformation',
    'generational shift to digital-native buyers',
    'API economy enabling faster integrations',
    'venture capital flowing into the space',
    'declining cost of LLM and AI infrastructure',
    'consumer demand for personalization',
  ],
  projected: [
    '$8B',
    '$25B',
    '$50B',
    '$100B',
    '$200B',
    '$400B',
    '$15B',
    '$35B',
    '$75B',
    '$150B',
    '$300B',
    '$10B',
    '$60B',
    '$120B',
    '$250B',
  ],
  year: ['2026', '2027', '2028', '2029', '2030'],
};

const engine: ToolEngine = {
  slug: 'solopreneur-market-size-estimator',
  title: 'Market Size Estimator',
  description: 'Get TAM, SAM, growth rate, and key driver estimates for any industry or product category.',
  category: 'A',
  inputs: [
    { name: 'topic', label: 'Industry or Product Category', placeholder: 'e.g. AI productivity tools, pet care', type: 'text' },
  ],
  clientConfig: { type: 'templates', templates, wordPools },
  generate(inputs) {
    return generateFromTemplates(templates, wordPools, inputs, 10);
  },
  staticExamples: [
    'Global SaaS & cloud software market: $300B+, growing 18-25% annually. Key segment: SMB-focused tools.',
    'e-learning & online education TAM estimate: $150B-$300B in 2028. Growth driver: shift to remote and async work.',
    'Market snapshot — creator economy: $10B-$30B total, API & developer tools sub-segment expanding at 25-35%.',
    'The fintech & personal finance industry is worth $30B-$80B, with mobile-first experiences as the fastest-growing slice (20-30%).',
    'For a solopreneur entering home fitness equipment: aim for subscription & membership ($500M-$2B), 14-18% annual growth, fueled by post-pandemic digital transformation.',
  ],
  faq: [
    { q: 'Where do these market size numbers come from?', a: 'They are illustrative estimates based on publicly reported industry data from sources like Statista, Gartner, McKinsey, and CB Insights. Use them for directional guidance and initial sizing, not for investor pitch decks — always verify with primary research.' },
    { q: 'What is the difference between TAM, SAM, and SOM?', a: 'TAM (Total Addressable Market) is the total global demand. SAM (Serviceable Addressable Market) is the portion you can realistically reach with your business model. SOM (Serviceable Obtainable Market) is what you can capture in the near term. This tool provides TAM and segment-level SAM estimates.' },
    { q: 'How do I use this for a niche product?', a: 'Start with the broad industry TAM, then narrow to your segment. If the broad industry is $50B and your segment is 10% of that, your SAM is roughly $5B. For a solopreneur, capturing even 0.1% of that is a $5M business.' },
    { q: 'Are growth rates accurate?', a: 'They represent typical ranges observed across these industries. Actual growth varies by region, timing, and competitive dynamics. Cross-reference with industry reports before making major decisions.' },
    { q: 'What is a "good" market size for a solopreneur?', a: 'A $500M-$5B SAM growing 10%+ annually is excellent. Anything under $100M is too niche for most investors but can still support a $1M-$3M/year lifestyle business if you dominate it.' },
  ],
  howToUse: [
    'Enter an industry or product category (e.g., "mental health apps", "DTC coffee").',
    'Click "Generate Estimates" to get 10 market-sizing perspectives.',
    'Each output gives TAM, growth rate, key segment, and market driver.',
    'Look for consensus ranges across multiple results — that is your ballpark estimate.',
    'Use these estimates to decide whether the market can support your revenue goals.',
  ],
};

registerEngine(engine);
