#!/usr/bin/env node
// P108 — CI guard for image bundle size (completes performance size triad).
//
// Why this exists:
//   The project ships social-preview PNGs in dist/og/ (one per page × 2 langs
//   = 200 OG images, auto-generated by satori). These load only when a URL is
//   scraped by Twitter / Slack / iMessage / etc., so they don't affect
//   first-paint, but they DO affect share-scraper bandwidth and
//   deploy-distribution size (the 46.6 MB of PNGs is shipped to the CDN on
//   every deploy even though only ~1 OG is fetched per share).
//
//   There are zero inline `<img>` tags in any page (verified 2026-07-27), so
//   page-load image weight is not a concern. This guard covers the OG bundle.
//
// Current baseline (2026-07-27):
//   - Files: 200 PNGs in dist/og/ (one per page × en + zh)
//   - Total: 46.6 MB
//   - Max per image: 316 KB
//   - p50 / p95: 292 / 309 KB
//   - Format: PNG (universal OG compatibility — most social platforms don't
//     accept WebP for og:image)
//
// Performance dimension triad status (HTML + JS + CSS + images):
//   - HTML size: page-size-guard (23rd)
//   - JS bundle: js-bundle-size-guard (27th, P106)
//   - CSS bundle: css-bundle-size-guard (28th, P107)
//   - Images:    image-size-guard (29th, P108) — this batch
//
// Build dependency:
//   - RUN_BUILD_TESTS=1 required (P23b skip-guard pattern, 29th build-dep suite)

import { test } from 'node:test';
import { strict as assert } from 'node:assert';
import { existsSync, readdirSync, statSync } from 'node:fs';
import { resolve } from 'node:path';
import { spawnSync } from 'node:child_process';

const root = resolve(import.meta.dirname, '..');

// Per-image budget: 500 KB. Current max is 316 KB, so 500 KB allows ~58%
// headroom. Satori OG image dimensions are 1200×630 — any future increase
// in dimension or quality settings would push past this threshold.
const MAX_OG_IMAGE_BYTES = 500 * 1024;

// Total bundle budget: 80 MB. Current total is 46.6 MB, so 80 MB allows
// ~72% headroom. Catches: (a) dimension increases, (b) quality bumps,
// (c) adding too many pages (each adds 2 OG images).
const MAX_OG_BUNDLE_BYTES = 80 * 1024 * 1024;

// P23b: skip cleanly when build-dep gate not set.
if (!process.env.RUN_BUILD_TESTS) {
  process.exit(0);
}

function ensureBuilt(): void {
  const probe = resolve(root, 'dist', 'en', 'about', 'index.html');
  if (existsSync(probe)) return;
  console.log('[p108] dist/ missing — running pnpm build...');
  const r = spawnSync('pnpm', ['build'], {
    cwd: root,
    stdio: 'inherit',
    shell: process.platform === 'win32',
  });
  assert.equal(r.status, 0, `pnpm build failed with status ${r.status}`);
}

interface ImageInfo {
  rel: string;
  bytes: number;
}

function getOgImages(): ImageInfo[] {
  const ogDir = resolve(root, 'dist', 'og');
  if (!existsSync(ogDir)) return [];
  const result: ImageInfo[] = [];
  for (const entry of readdirSync(ogDir, { withFileTypes: true })) {
    if (entry.isFile() && entry.name.endsWith('.png')) {
      const full = resolve(ogDir, entry.name);
      result.push({ rel: entry.name, bytes: statSync(full).size });
    }
  }
  return result;
}

test('no OG image exceeds per-image budget (500 KB)', () => {
  ensureBuilt();
  const images = getOgImages();

  assert.ok(
    images.length >= 1,
    'Expected at least one OG image in dist/og/. Run pnpm build first.',
  );

  const violations: ImageInfo[] = [];
  for (const img of images) {
    if (img.bytes > MAX_OG_IMAGE_BYTES) {
      violations.push(img);
    }
  }

  // Distribution stats (observability)
  const sizes = images.map(i => i.bytes).sort((a, b) => a - b);
  const n = sizes.length;
  const max = sizes[n - 1];
  const p95 = sizes[Math.floor(n * 0.95)];
  const p50 = sizes[Math.floor(n / 2)];
  const min = sizes[0];

  console.log(
    `[p108] OG images: ${n} files | min ${(min / 1024).toFixed(0)} KB | p50 ${(p50 / 1024).toFixed(0)} KB | p95 ${(p95 / 1024).toFixed(0)} KB | max ${(max / 1024).toFixed(0)} KB`,
  );

  assert.equal(
    violations.length,
    0,
    `OG image size violations (${violations.length}, threshold ${MAX_OG_IMAGE_BYTES / 1024} KB):\n` +
      violations.slice(0, 20).map(v => `  - ${v.rel}: ${(v.bytes / 1024).toFixed(1)} KB`).join('\n') +
      (violations.length > 20 ? `\n  ... and ${violations.length - 20} more` : '') +
      `\n\nOG images are generated by satori at 1200×630. If a future batch pushes past ` +
      `500 KB, check satori config (font loading, dimensions, dpr settings).`,
  );
});

test('total OG image bundle stays under budget (80 MB)', () => {
  ensureBuilt();
  const images = getOgImages();

  assert.ok(
    images.length >= 1,
    'Expected at least one OG image in dist/og/. Run pnpm build first.',
  );

  let totalBytes = 0;
  for (const img of images) {
    totalBytes += img.bytes;
  }

  console.log(
    `[p108] OG bundle total: ${(totalBytes / 1024 / 1024).toFixed(1)} MB (${images.length} files)`,
  );

  assert.ok(
    totalBytes <= MAX_OG_BUNDLE_BYTES,
    `OG bundle exceeds ${MAX_OG_BUNDLE_BYTES / 1024 / 1024} MB budget: ` +
      `${(totalBytes / 1024 / 1024).toFixed(1)} MB actual across ${images.length} images. ` +
      `Bundle grows with: (a) per-image size increases, (b) adding new pages (each ` +
      `adds 2 OG images — one per locale).`,
  );
});