/**
 * A3 Decision Report builder.
 *
 * Per spec §3.3:
 *   - 2 formats: PDF (lazy-import jsPDF) + HTML
 *   - Sections: Header, Calc name + URL, Inputs table, Outputs table
 *     (with health band emoji if available), Decision recommendation
 *     (if available), Footer with date
 *   - PDF filename: forgeflowkit-{slug}-{YYYY-MM-DD}.pdf
 *   - Last-used config persisted in ffk.reportConfig.v1
 *
 * Lazy-loads jsPDF on first call (spec §1.2: ~50KB, not blocking page render).
 */

import { safeStorageGet, safeStorageSet, STORAGE_KEYS } from './storage.ts';

export interface ReportInput {
  calcSlug: string;
  title: string;
  inputs: Record<string, number | string>;
  outputs: Record<string, number | string>;
  healthBand?: string;
  recommendation?: string;
}

export interface ReportConfig {
  titleTemplate: string;
  format: 'pdf' | 'html';
}

const DEFAULT_CONFIG: ReportConfig = {
  titleTemplate: 'ForgeFlowKit · {calcSlug} · {date}',
  format: 'pdf',
};

// Lazy jsPDF loader — cached after first call.
let _jsPDFPromise: Promise<any> | null = null;
function loadJsPDF(): Promise<any> {
  if (!_jsPDFPromise) {
    _jsPDFPromise = import('jspdf').then(m => m.default || m.jsPDF);
  }
  return _jsPDFPromise;
}

export type ReportResult =
  | { ok: true; filename: string; blob?: Blob; html?: string }
  | { ok: false; reason: 'pdf_load_failed' | 'unknown' };

export async function generateReport(input: ReportInput, format: 'pdf' | 'html'): Promise<ReportResult> {
  const date = new Date().toISOString().slice(0, 10);
  const filename = `forgeflowkit-${input.calcSlug}-${date}.${format}`;

  if (format === 'html') {
    return { ok: true, filename, html: buildHtml(input, date) };
  }

  // PDF path
  try {
    const JsPDF = await loadJsPDF();
    const doc = new JsPDF();
    buildPdf(doc, input, date);
    const blob = doc.output('blob');
    return { ok: true, filename, blob };
  } catch (err) {
    console.error('[enterprise/report] jsPDF load failed:', err);
    return { ok: false, reason: 'pdf_load_failed' };
  }
}

function buildHtml(input: ReportInput, date: string): string {
  const rows = (obj: Record<string, number | string>) =>
    Object.entries(obj).map(([k, v]) => `<tr><td>${escape(k)}</td><td>${escape(String(v))}</td></tr>`).join('');
  const band = input.healthBand ? `<p><strong>Health:</strong> ${escape(input.healthBand)}</p>` : '';
  const reco = input.recommendation ? `<p><strong>Recommendation:</strong> ${escape(input.recommendation)}</p>` : '';
  return `<!doctype html><html><head><meta charset="utf-8"><title>${escape(input.title)}</title>
<style>body{font-family:system-ui,sans-serif;max-width:720px;margin:2rem auto;padding:0 1rem;color:#1f2937}
h1{margin-bottom:0.25rem}table{border-collapse:collapse;width:100%;margin:1rem 0}
th,td{border:1px solid #e5e7eb;padding:0.5rem;text-align:left}
th{background:#f9fafb}</style></head><body>
<h1>${escape(input.title)}</h1>
<p><strong>Calculator:</strong> ${escape(input.calcSlug)} · <strong>Date:</strong> ${date}</p>
<h2>Inputs</h2><table><tbody>${rows(input.inputs)}</tbody></table>
<h2>Outputs</h2><table><tbody>${rows(input.outputs)}</tbody></table>
${band}${reco}
<hr><p><small>Generated by ForgeFlowKit · ${date}</small></p>
</body></html>`;
}

function buildPdf(doc: any, input: ReportInput, date: string): void {
  doc.setFontSize(18);
  doc.text(input.title, 14, 20);
  doc.setFontSize(10);
  doc.text(`Calculator: ${input.calcSlug}`, 14, 30);
  doc.text(`Date: ${date}`, 14, 36);
  doc.text('Inputs', 14, 48);
  let y = 54;
  for (const [k, v] of Object.entries(input.inputs)) {
    doc.text(`${k}: ${v}`, 14, y);
    y += 6;
  }
  y += 6;
  doc.text('Outputs', 14, y);
  y += 6;
  for (const [k, v] of Object.entries(input.outputs)) {
    doc.text(`${k}: ${v}`, 14, y);
    y += 6;
  }
  if (input.healthBand) { doc.text(`Health: ${input.healthBand}`, 14, y + 6); y += 12; }
  if (input.recommendation) { doc.text(`Recommendation: ${input.recommendation}`, 14, y + 6); }
  doc.setFontSize(8);
  doc.text(`Generated by ForgeFlowKit · ${date}`, 14, 280);
}

export function saveReportConfig(config: ReportConfig): boolean {
  return safeStorageSet(STORAGE_KEYS.reportConfig, config);
}

export function getReportConfig(): ReportConfig {
  return safeStorageGet<ReportConfig>(STORAGE_KEYS.reportConfig, DEFAULT_CONFIG);
}

function escape(s: string): string {
  return s.replace(/[&<>"']/g, c => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[c]!));
}
