/**
 * Extracts all wordPool string values from engine files, translates them
 * to Chinese via Google Translate (free, unofficial API), and caches results.
 *
 * Usage: npx tsx scripts/translate-wordpools.ts
 *
 * Supports HTTPS_PROXY for regions where Google is blocked.
 */

import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ENGINES_DIR = join(__dirname, '..', 'src', 'engines');
const CACHE_FILE = join(__dirname, '..', 'src', 'i18n', 'wordpool-cache.ts');

const SLEEP_MS = 200; // Be polite, avoid rate limiting

async function sleep(ms: number) {
  return new Promise(r => setTimeout(r, ms));
}

/** Extract all unique wordPool string values from engine files */
function extractWordPools(): string[] {
  const files = readdirSync(ENGINES_DIR).filter(f => f.endsWith('.ts') && f !== 'index.ts');
  const allValues = new Set<string>();

  for (const file of files) {
    const content = readFileSync(join(ENGINES_DIR, file), 'utf-8');

    // Match the wordPools object block
    const poolMatch = content.match(/const wordPools[\s\S]*?=\s*\{([\s\S]*?)\n\};/);
    if (!poolMatch) continue;

    // Extract array contents: ['val1', 'val2', ...]
    const arrays = poolMatch[0].matchAll(/\[([^\]]*)\]/g);
    for (const arr of arrays) {
      // Extract single-quoted strings from within each array
      const strings = arr[1].matchAll(/'([^']+)'/g);
      for (const s of strings) {
        const val = s[1];
        // Skip pure numbers and very short strings
        if (/^\d+$/.test(val)) continue;
        if (/^[+\-$.\d]+$/.test(val)) continue; // dollar amounts, percentages
        if (val.length < 2) continue;
        // Skip strings that look like TypeScript code fragments
        if (val.includes('\n') || val.includes('  ') || val.startsWith('//')) continue;
        allValues.add(val);
      }
    }
  }

  return Array.from(allValues).sort();
}

/** Load existing cache */
function loadCache(): Map<string, string> {
  const cache = new Map<string, string>();
  if (!existsSync(CACHE_FILE)) return cache;
  const content = readFileSync(CACHE_FILE, 'utf-8');
  // Parse: "en": "zh"
  const matches = content.matchAll(/"([^"]+)": "([^"]+)"/g);
  for (const m of matches) {
    cache.set(m[1], m[2]);
  }
  return cache;
}

/** Save cache as TypeScript module */
function saveCache(cache: Map<string, string>) {
  const dir = dirname(CACHE_FILE);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

  const entries = Array.from(cache.entries())
    .sort(([a], [b]) => a.localeCompare(b));

  let ts = '// Auto-generated by scripts/translate-wordpools.ts\n';
  ts += '// Do not edit manually. Regenerate with: npx tsx scripts/translate-wordpools.ts\n\n';
  ts += 'export const wordPoolTranslations: Record<string, string> = {\n';
  for (const [en, zh] of entries) {
    ts += `  "${en.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}": "${zh.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}",\n`;
  }
  ts += '};\n';

  writeFileSync(CACHE_FILE, ts);
  console.log(`Cache saved: ${entries.length} entries → ${CACHE_FILE}`);
}

let _translator: any = null;
let _proxyAgent: any = undefined;

/** Translate a single string via Google Translate */
async function translateOne(text: string): Promise<string> {
  if (!_translator) {
    const { translate } = await import('@vitalets/google-translate-api');
    _translator = translate;

    // Set up proxy if HTTPS_PROXY is configured
    const proxy = process.env.HTTPS_PROXY || process.env.HTTP_PROXY;
    if (proxy) {
      try {
        const undici = await import('undici');
        _proxyAgent = new undici.ProxyAgent({ uri: proxy });
        console.log(`Using proxy: ${proxy}`);
      } catch {
        console.warn('Proxy configured but undici unavailable; requests will go direct');
      }
    }
  }

  const fetchOptions: any = {};
  if (_proxyAgent) {
    fetchOptions.dispatcher = _proxyAgent;
  }

  try {
    const result = await _translator!(text, {
      from: 'en',
      to: 'zh-CN',
      fetchOptions,
    });
    return result.text || text;
  } catch (e: any) {
    if (e?.code === 'ERR_INVALID_URL' || e?.message?.includes('fetch')) {
      console.warn(`  Network error — is proxy configured? Skipping.`);
    }
    return text;
  }
}

async function main() {
  console.log('Extracting word pools from engines...');
  const values = extractWordPools();
  console.log(`Found ${values.length} unique strings to translate`);

  const cache = loadCache();
  console.log(`Loaded ${cache.size} existing translations from cache`);

  const untranslated = values.filter(v => !cache.has(v));
  console.log(`${untranslated.length} strings need translation`);

  if (untranslated.length === 0) {
    console.log('All strings already translated!');
    saveCache(cache);
    return;
  }

  let translated = 0;
  for (const text of untranslated) {
    process.stdout.write(`[${translated + 1}/${untranslated.length}] "${text.slice(0, 50)}${text.length > 50 ? '...' : ''}" → `);
    const result = await translateOne(text);
    console.log(`"${result.slice(0, 50)}${result.length > 50 ? '...' : ''}"`);
    cache.set(text, result);
    translated++;

    // Save progress every 20 items
    if (translated % 20 === 0) {
      saveCache(cache);
    }

    await sleep(SLEEP_MS);
  }

  saveCache(cache);
  console.log(`\nDone! ${translated} new translations. Total: ${cache.size} entries.`);
}

main().catch(e => {
  console.error('Translation failed:', e);
  process.exit(1);
});
